In [3]:
import numpy as np

In [4]:
forecast_h = {'total':100,'A':50,'B':60,'AA':30,'AB':30,'AC':10,'BA':30,'BB':20}

In [5]:
forecast_h['total']

100

In [6]:
forecast_h['AA'] + forecast_h['AB'] + forecast_h['AC'] + forecast_h['BA'] + forecast_h['BB']

120

In [7]:
S = np.array([[1,1,1,1,1], #Total: AA + AB + AC + BA + BB
              [1,1,1,0,0], #A: AA +AB + AC
              [0,0,0,1,1], #B: BA + BB
              [1,0,0,0,0], #AA
              [0,1,0,0,0], #AB
              [0,0,1,0,0], #AC
              [0,0,0,1,0], #BA
              [0,0,0,0,1]] #BB
              ) 

In [8]:
m,n = S.shape
print(m,m)

8 8


In [9]:
O = np.zeros([n,m-n])
O

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
I = np.identity(n)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
G = np.hstack([O,I])
G

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
y_hat = np.array(list(forecast_h.values()))
y_hat

array([100,  50,  60,  30,  30,  10,  30,  20])

In [13]:
G * y_hat

array([[ 0.,  0.,  0., 30.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 30.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 30.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 20.]])

In [14]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
S @ G @ S

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
G @ S

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
G * y_hat

array([[ 0.,  0.,  0., 30.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 30.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 30.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 20.]])

In [38]:
y_hat

array([100,  50,  60,  30,  30,  10,  30,  20])

In [36]:
y_rec = S @ G @ y_hat
y_rec

array([120.,  70.,  50.,  30.,  30.,  10.,  30.,  20.])

In [47]:
G @ y_hat

array([30., 30., 10., 30., 20.])

In [21]:
y_hat

array([100,  50,  60,  30,  30,  10,  30,  20])

In [ ]:
y = [100,50,50,30,10,10,30,20] #valor real e coerente

In [25]:
y - y_hat

array([  0,   0, -10,   0, -20,   0,   0,   0])

In [26]:
b = [30,  30,  10,  30,  20]

In [34]:
(S @ G @ y)

array([100.,  50.,  50.,  30.,  10.,  10.,  30.,  20.])

In [32]:
Beta = G @ y_hat
Beta

array([30., 30., 10., 30., 20.])

In [33]:
S @ Beta

array([120.,  70.,  50.,  30.,  30.,  10.,  30.,  20.])

In [39]:
e_hat = y - y_hat
e_rec = y - y_rec 

In [42]:
np.cov(e_hat)

array(55.35714286)

In [48]:
G @ y_hat

array([30., 30., 10., 30., 20.])

In [41]:
e_hat @ e_rec

400.0